<a href="https://colab.research.google.com/github/rahulskhatav/DataScienceLab/blob/main/Principal_Component_Analysis_from_Scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Principal Component Analysis from Scratch
* Name: Rahul Sunil Khatav
* RollNo: 197243
* Class: CSE III B
* CS356 Data Science Lab

In [46]:
# imports
import numpy as np
import pandas as pd
from google.colab import files
from matplotlib import pyplot as plt
import seaborn as sb

uploaded = files.upload()

Saving iris.data to iris (4).data


> Importing and Splitting the Dataset

In [53]:
# loading the dataset
df = pd.read_csv('iris.data', header=None, names=['sepal length','sepal width','petal length','petal width','Y'])
print("Dataset:", df.shape)
print(df.head())

# splitting into X and Y
X = df.iloc[:, 0:4]
Y = df.iloc[:, 4]
print("X:", X.shape)
print("Y:", Y.shape)

Dataset: (150, 5)
   sepal length  sepal width  petal length  petal width            Y
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa
X: (150, 4)
Y: (150,)


> Centering around the mean

In [21]:
X_mean = X - np.mean(X, axis=0)
print(X_mean.head())

          0      1         2         3
0 -0.743333  0.446 -2.358667 -0.998667
1 -0.943333 -0.054 -2.358667 -0.998667
2 -1.143333  0.146 -2.458667 -0.998667
3 -1.243333  0.046 -2.258667 -0.998667
4 -0.843333  0.546 -2.358667 -0.998667


> Calculating the Covariance Matrix

In [22]:
cov_matrix = np.cov(X_mean, rowvar=False)
print(cov_matrix)

[[ 0.68569351 -0.03926846  1.27368233  0.5169038 ]
 [-0.03926846  0.18800403 -0.32171275 -0.11798121]
 [ 1.27368233 -0.32171275  3.11317942  1.29638747]
 [ 0.5169038  -0.11798121  1.29638747  0.58241432]]


> Calculating Eigen Values and Vectors

In [23]:
eigen_val, eigen_vec = np.linalg.eigh(cov_matrix)
print("Eigen Values:\n", eigen_val)
print("Eigen Vector:\n", eigen_vec)

Eigen Values:
 [0.02368303 0.07852391 0.24224357 4.22484077]
Eigen Vector:
 [[ 0.31725455  0.58099728  0.65653988 -0.36158968]
 [-0.32409435 -0.59641809  0.72971237  0.08226889]
 [-0.47971899 -0.07252408 -0.1757674  -0.85657211]
 [ 0.75112056 -0.54906091 -0.07470647 -0.35884393]]


> Sort the Eigen Values to compute Variability

In [29]:
sorted_indices = np.argsort(-eigen_val)
eigen_val_sorted = eigen_val[sorted_indices]
eigen_vec_sorted = eigen_vec[sorted_indices]
print(eigen_val_sorted)

[4.22484077 0.24224357 0.07852391 0.02368303]


> Selecting k = 2 (because easier to plot)

In [35]:
subset_eigen_vector = eigen_vec_sorted[:, 0:2]
print("Eigen Subset:", subset_eigen_vector.shape)

# reduced matrix is the transpose(eigen_vec_sorted.tranpose() * X_mean.transpose())
X_reduced = np.dot(subset_eigen_vector.transpose(), X_mean.transpose()).transpose()
print("X_reduced:", X_reduced.shape)

Eigen Subset: (4, 2)
X_reduced: (150, 2)


In [60]:
df = pd.DataFrame(X_reduced, columns=['PCA1', 'PCA2'])
df = pd.concat([df, pd.DataFrame(Y)], axis = 1)

print(df.head(5))
# sb.scatterplot(data = df , hue = 'Y' , s = 60 , palette= 'icefire')

       PCA1      PCA2            Y
0 -0.324689  1.202318  Iris-setosa
1 -0.235053  1.348393  Iris-setosa
2 -0.448812  1.503342  Iris-setosa
3 -0.540771  1.446217  Iris-setosa
4 -0.447773  1.249972  Iris-setosa
